# FileManager Pro - Docker Compose Configuration
# Development environment setup

version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      target: development
    container_name: filemanager-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - uploads_data:/var/www/html/uploads
      - logs_data:/var/www/html/logs
    environment:
      - ENVIRONMENT=development
      - DEBUG_MODE=true
      - DB_HOST=db
      - DB_NAME=filemanager_dev
      - DB_USER=filemanager
      - DB_PASS=dev_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - filemanager_network

  # Database service
  db:
    image: mysql:8.0
    container_name: filemanager-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=filemanager_dev
      - MYSQL_USER=filemanager
      - MYSQL_PASSWORD=dev_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - filemanager_network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: filemanager-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_password
      - UPLOAD_LIMIT=100M
    depends_on:
      - db
    networks:
      - filemanager_network

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: filemanager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - filemanager_network

# Named volumes
volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local
  redis_data:
    driver: local

# Networks
networks:
  filemanager_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
